# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cmt < Formula
  desc "AI-powered automatic git commit message generator"
  homepage "https://github.com/makesikann/cmt"
  version "0.1.0"

  on_macos do
    on_intel do
      url "https://github.com/makesikann/cmt/releases/download/v0.1.0/cmt_Darwin_x86_64.tar.gz"
      sha256 "d72b95c084b3cfc8fb6a681e63fb2e33d0fc2bc38c16e83ffb727d692393438c"

      def install
        bin.install "cmt"
      end
    end
    on_arm do
      url "https://github.com/makesikann/cmt/releases/download/v0.1.0/cmt_Darwin_arm64.tar.gz"
      sha256 "af8215008136920aec8ef08bb285612c8c156b827e3cd344497fbcdc31b5d950"

      def install
        bin.install "cmt"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/makesikann/cmt/releases/download/v0.1.0/cmt_Linux_x86_64.tar.gz"
        sha256 "ec1cdbe0271ae1eb60e295ce59d43f4dea1a383fa9a961cfcd93449197634fa9"

        def install
          bin.install "cmt"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/makesikann/cmt/releases/download/v0.1.0/cmt_Linux_arm64.tar.gz"
        sha256 "00b61d50f0729c24f776cb58ce7955bb116c879adcb17662820034a55cfa4545"

        def install
          bin.install "cmt"
        end
      end
    end
  end
end
